search:
	@echo " Compile Search ...";
	g++ lsh_main.cpp -o search
cube:
	@echo " Compile Binary Hyper Cube ...";
	g++ cube_main.cpp -o cube
cluster:
	@echo " Compile Clustering ...";
	g++ cluster_main.cpp -o cluster
